name: CI

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - dev
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        run: yarn

      - name: Lint
        run: yarn run lint

      - name: Build
        run: yarn build